apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: hefis/task-managements:test.1.12
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: DATABASE_HOST
              value: $(MYSQL_SERVICE_HOST)
            - name: DATABASE_PORT
              value: $(MYSQL_SERVICE_PORT)
          envFrom:
            - secretRef:
                name: api-secret
            - configMapRef:
                name: api-configmap
